//Avatar2D.jsx
import styles from './Avatar2D.module.css';
import { useRef } from 'react';

export default function Avatar2D({emoji = "Happy"}) {
    // Đổi tên ref cho rõ nghĩa
    const cardRef = useRef(null);

    function handleFullscreen() {
        // Sử dụng cardRef
        const el = cardRef.current; 
        if (!el) return;
        
        // Cross-browser requestFullscreen
        const req = el.requestFullscreen || el.webkitRequestFullscreen || el.msRequestFullscreen;
        if (req) req.call(el);
    }

    return (
        <div className={styles.container}>
            {/* Sử dụng styles.card để có nền gradient và bóng đổ.
              Đặt ref và onClick ở đây.
            */}

            <div className={styles.emojiContainer}>
                {/* Icon {emoji} */}
                <img
                    src={`/emojis/${emoji}.png`}
                    alt={emoji}
                    className={styles.emoji}
                    width="64"
                    height="64"
                />
            </div>
            <div className={styles.card} ref={cardRef} >
                <img
                    src="/Avatar2D/Neutral.webp"
                    alt="2D Avatar"
                    className={styles.media}
                    width="1200"
                    height="1600"
                />
            </div>
            {/* Không còn phần .meta hay .credit */}
            {/* Thêm thông báo về chất lượng ảnh AI chính giữa */}
            {/* <div className={'Notification'} style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', padding: '12px', background: 'rgba(0, 0, 0, 0.5)', color: '#e81b1bff', borderRadius: '8px', fontSize: '24px', fontWeight: '900' }}>
                <div>Warning: 2D Avatar generated by AI may contain artifacts or inaccuracies.</div>
                <div>This is pre-build version for testing only.</div>
            </div> */}
        </div>
    );
}